// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-default-playlists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { defaultPlaylists, exercisePlaylists } from "npm:@/data/defaultPresets";
var list_default_playlists_default = defineTool({
  name: "list_default_playlists",
  title: "List default BeatMaster playlists",
  description: "List BeatMaster's built-in playlists (band setlists and instrument exercises), each with their songs, BPMs, and time signatures.",
  inputSchema: {
    include_exercises: z.boolean().optional().describe("Include the \u{1F393} Exerc\xEDcios instrument-training playlists. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ include_exercises }) => {
    const includeExercises = include_exercises ?? true;
    const all = includeExercises ? [...defaultPlaylists, ...exercisePlaylists] : defaultPlaylists;
    const summary = all.map((p) => ({
      name: p.name,
      band: p.band,
      songCount: p.songs.length,
      songs: p.songs.map((s) => ({
        name: s.name,
        artist: s.artist,
        bpm: s.bpm,
        timeSignature: s.timeSignature,
        durationSeconds: s.duration,
        notes: s.notes
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { playlists: summary }
    };
  }
});

// src/lib/mcp/tools/search-music-metadata.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var MB_URL = "https://musicbrainz.org/ws/2/recording";
var search_music_metadata_default = defineTool2({
  name: "search_music_metadata",
  title: "Search music metadata (MusicBrainz)",
  description: "Search the MusicBrainz recording database for a song/artist. Returns matches with title, artist, release, and MBID \u2014 useful for enriching BeatMaster setlists.",
  inputSchema: {
    query: z2.string().min(1).max(200).describe("Song title, artist, or 'title artist' query."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (1-25). Default 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const url = `${MB_URL}?query=${encodeURIComponent(query)}&limit=${limit ?? 5}&fmt=json`;
    try {
      const res = await fetch(url, {
        headers: { "User-Agent": "BeatMaster-MCP/0.1.0 (https://beatmaster.lovable.app)" }
      });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `MusicBrainz error: ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      const results = (data.recordings ?? []).map((r) => ({
        title: r.title,
        artist: r["artist-credit"]?.map((a) => a.name).join(", "),
        release: r.releases?.[0]?.title,
        lengthMs: r.length,
        mbid: r.id,
        score: r.score
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
        structuredContent: { results }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Fetch failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/bpm-utils.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var bpm_utils_default = defineTool3({
  name: "bpm_utils",
  title: "BPM & tempo utilities",
  description: "Convert between BPM, milliseconds per beat, and beats/bars for a given duration and time signature. Handy for planning setlist timing.",
  inputSchema: {
    bpm: z3.number().min(20).max(400).describe("Tempo in beats per minute."),
    timeSignature: z3.string().optional().describe("Time signature like '4/4', '3/4', '6/8'. Defaults to '4/4'."),
    durationSeconds: z3.number().min(0).optional().describe("Optional song duration; if provided, returns total beats and bars.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bpm, timeSignature, durationSeconds }) => {
    const ts = timeSignature ?? "4/4";
    const [numStr] = ts.split("/");
    const beatsPerBar = parseInt(numStr, 10) || 4;
    const msPerBeat = 6e4 / bpm;
    const result = {
      bpm,
      timeSignature: ts,
      beatsPerBar,
      msPerBeat: Math.round(msPerBeat * 100) / 100,
      secondsPerBar: Math.round(msPerBeat * beatsPerBar / 10) / 100
    };
    if (durationSeconds != null) {
      const totalBeats = durationSeconds * bpm / 60;
      result.totalBeats = Math.round(totalBeats * 100) / 100;
      result.totalBars = Math.round(totalBeats / beatsPerBar * 100) / 100;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "beatmaster-mcp",
  title: "BeatMaster MCP",
  version: "0.1.0",
  instructions: "Tools for BeatMaster \u2014 a performance app with metronome, setlist, and sampler. Use `list_default_playlists` to browse built-in band/exercise setlists, `search_music_metadata` to look up songs on MusicBrainz, and `bpm_utils` for tempo/bar calculations.",
  tools: [list_default_playlists_default, search_music_metadata_default, bpm_utils_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
