// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-default-playlists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/data/defaultPresets.ts
function song(name, bpm, ts, notes = "", artist = "", duration) {
  return { id: crypto.randomUUID(), name, bpm, timeSignature: ts, notes, artist, duration };
}
function playlist(name, songs, band = "Geral") {
  return { id: crypto.randomUUID(), name, songs, band };
}
var defaultPlaylists = [
  playlist("Rock Covers", [
    song("TIME", 128, "4/4", "", "", 300),
    song("STORMBRINGER", 170, "4/4", "", "Deep Purple", 270),
    song("REBEL YELL", 165, "4/4", "", "Billy Idol", 280),
    song("SOMEKE", 114, "4/4"),
    song("LOVE AINT NO STRANGER", 108, "4/4", "", "Whitesnake"),
    song("HELTER", 164, "4/4", "", "The Beatles"),
    song("EPIC", 92, "4/4", "", "Faith No More", 295),
    song("PERFECT STRANGER", 118, "4/4", "", "Deep Purple"),
    song("WHRATCHILD", 200, "4/4", "", "Iron Maiden"),
    song("SHOUT", 98, "4/4", "", "Tears for Fears"),
    song("MEDLEY ALIVE>>>BLACK", 76, "4/4", "Medley"),
    song("MEDLEY NO QUARTER>>>>KASHMIR", 80, "4/4", "Medley"),
    song("TOMORROW", 146, "4/4"),
    song("HYSTERIA", 93, "4/4", "", "Def Leppard"),
    song("IMMIGRANT", 112, "4/4", "", "Led Zeppelin"),
    song("VASOLINE", 178, "4/4", "", "Stone Temple Pilots"),
    song("MEDLEY PLUSH>>>CRAZY", 144, "4/4", "Medley"),
    song("MAN IN THE BOX", 106, "4/4", "", "Alice in Chains"),
    song("MEDLEY SHOWME HOW TO LIVE>>>EVEN FLOW", 104, "4/4", "Medley"),
    song("HAVE A CIGAR", 124, "4/4", "", "Pink Floyd"),
    song("COME TOGETHER", 82, "4/4", "", "The Beatles"),
    song("LIFTMEUP", 148, "4/4"),
    song("ROYALS", 85, "4/4", "Sampler"),
    song("THEM BONES", 168, "7/8", "Alice in Chains", "Alice in Chains"),
    song("LONELY TRAIN", 124, "4/4"),
    song("SABBATH BLOODY SABBATH", 148, "4/4", "", "Black Sabbath"),
    song("ROLING IN THE DEEP", 105, "4/4", "", "Adele"),
    song("AREIALS", 162, "4/4", "", "System of a Down"),
    song("KILLING IN THE NAME OF", 88, "4/4", "", "Rage Against the Machine"),
    song("WICKED GAME", 112, "4/4", "", "Chris Isaak"),
    song("Are You Gonna Go My Way", 130, "4/4", "", "Lenny Kravitz"),
    song("Song 2", 130, "4/4", "", "Blur"),
    song("Use Somebody", 137, "4/4", "", "Kings of Leon"),
    song("Seven Nation Army", 123, "4/4", "", "The White Stripes"),
    song("Smells Like Teen Spirit", 118, "4/4", "", "Nirvana"),
    song("Wonderwall", 87, "4/4", "", "Oasis"),
    song("Creep", 92, "4/4", "", "Radiohead"),
    song("Losing My Religion", 125, "4/4", "", "R.E.M."),
    song("Under the Bridge", 84, "4/4", "", "Red Hot Chili Peppers"),
    song("Zombie", 86, "4/4", "", "The Cranberries")
  ], "Covers Variados"),
  playlist("Metallica", [
    song("NOTHING ELSE", 142, "6/8", "", "Metallica"),
    song("FUEL", 104, "4/4", "", "Metallica"),
    song("MEDLEY WELCOME HOME>>>IDISAPPEAR", 109, "4/4", "Medley", "Metallica"),
    song("INTRO FIGHT WITH FIRE>>>CREEPING DEATH", 198, "4/4", "Medley", "Metallica"),
    song("HUMAN", 100, "4/4", "Drop C", "Metallica"),
    song("UNFORGIVEN 1 INTRO", 138, "4/4", "", "Metallica"),
    song("UNFORGIVEN 2 DIRETO", 138, "4/4", "", "Metallica"),
    song("ENTER SANDMAN", 123, "4/4", "", "Metallica"),
    song("SAD BUT TRUE", 92, "4/4", "", "Metallica"),
    song("UNAMED", 150, "4/4", "", "Metallica"),
    song("The Day That Never Comes", 146, "4/4", "", "Metallica"),
    song("Moth Into Flame", 108, "4/4", "", "Metallica"),
    song("Wherever I May Roam", 132, "4/4", "", "Metallica"),
    song("King Nothing", 112, "4/4", "", "Metallica"),
    song("The Memory Remains", 148, "4/4", "", "Metallica")
  ], "Metallica Tribute"),
  playlist("Metallica Completa", [
    song("HINO NACIONAL", 120, "4/4"),
    song("EXSTASY OF GOLD", 128, "4/4", "", "Ennio Morricone"),
    song("KUTHULU", 120, "4/4", "", "Metallica"),
    song("CREEPING", 198, "4/4", "", "Metallica"),
    song("WHISKEY", 133, "4/4", "", "Metallica"),
    song("UNFORGIVEN 2 DIRETO", 138, "4/4", "", "Metallica"),
    song("FUEL", 104, "4/4", "", "Metallica"),
    song("MEMORY REMAINS", 148, "4/4", "", "Metallica"),
    song("WELCOME HOME", 108, "4/4", "", "Metallica"),
    song("UNFORGIVEN 1 INTRO", 138, "4/4", "", "Metallica"),
    song("ONE", 108, "4/4", "", "Metallica"),
    song("FADE", 114, "4/4", "", "Metallica"),
    song("MASTER", 212, "4/4", "", "Metallica"),
    song("SEEK", 140, "4/4", "", "Metallica"),
    song("BELL", 118, "4/4", "", "Metallica"),
    song("TURN THE PAGE", 76, "4/4", "", "Metallica"),
    song("ENTER SANDMAN", 123, "4/4", "", "Metallica"),
    song("ECXTASY OF GOLD INTRO", 128, "4/4", "", "Metallica"),
    song("UNTIL SLEEPS", 114, "4/4", "", "Metallica"),
    song("WHEREVER", 132, "4/4", "", "Metallica"),
    song("HARDWIRED", 178, "4/4", "", "Metallica"),
    song("SAD BUT TRUE", 92, "4/4", "", "Metallica"),
    song("ORION", 130, "4/4", "", "Metallica"),
    song("Battery", 190, "4/4", "", "Metallica"),
    song("Blackened", 186, "7/8", "Riff principal", "Metallica"),
    song("Harvester of Sorrow", 118, "4/4", "", "Metallica"),
    song("...And Justice for All", 94, "4/4", "", "Metallica"),
    song("Disposable Heroes", 220, "4/4", "", "Metallica")
  ], "Metallica Tribute"),
  playlist("Nu-Metal Mix", [
    song("Rotting in Vain", 106, "4/4", "", "Korn"),
    song("Insane!", 94, "4/4", "", "Korn"),
    song("Blind", 95, "4/4", "Pad Subgrave", "Korn"),
    song("A.D.I.D.A.S.", 115, "4/4", "", "Korn"),
    song("Freak on a Leash", 103, "4/4", "", "Korn"),
    song("Thoughtless", 78, "4/4", "", "Korn"),
    song("Did My Time", 96, "4/4", "", "Korn"),
    song("A Place for My Head", 130, "4/4", "", "Linkin Park"),
    song("My Way", 98, "4/4", "", "Limp Bizkit"),
    song("Break Stuff", 100, "4/4", "", "Limp Bizkit"),
    song("Duality", 145, "4/4", "", "Slipknot"),
    song("Falling Away from Me", 104, "4/4", "Pad, Mini China, Tambourine", "Korn"),
    song("Coming Undone", 100, "4/4", "Claps", "Korn"),
    song("Another Brick in the Wall", 100, "4/4", "", "Pink Floyd"),
    song("Enjoy the Silence", 113, "4/4", "", "Depeche Mode"),
    song("Roots", 120, "4/4", "", "Sepultura"),
    song("Tear Away", 140, "4/4", "MPC", "Drowning Pool"),
    song("Denial", 105, "4/4", "", "Sevendust"),
    song("Sic", 190, "4/4", "", "Slipknot"),
    song("The Heretic Anthem", 204, "4/4", "", "Slipknot"),
    song("People = Shit", 128, "4/4", "", "Slipknot"),
    song("My Generation", 105, "4/4", "", "Limp Bizkit"),
    song("Rolling", 100, "4/4", "", "Limp Bizkit"),
    song("Here to Stay", 100, "4/4", "", "Korn"),
    song("Shoots and Leaders", 110, "4/4", "Intro"),
    song("Nookie", 98, "4/4", "", "Limp Bizkit"),
    song("Wait and Bleed", 190, "4/4", "", "Slipknot"),
    song("Last Resort", 90, "4/4", "", "Papa Roach"),
    song("Bodies", 128, "4/4", "", "Drowning Pool"),
    song("Click Click Boom", 100, "4/4", "", "Saliva")
  ], "Banda New Metal"),
  playlist("Slipknot", [
    song("NAMELESS", 210, "4/4", "", "Slipknot"),
    song("MY PLEAGUE", 172, "4/4", "", "Slipknot"),
    song("BEFORE", 135, "4/4", "", "Slipknot"),
    song("SPIT IT OUT", 144, "4/4", "", "Slipknot"),
    song("EYELES", 192, "4/4", "", "Slipknot"),
    song("LEFT BEHIND", 155, "4/4", "", "Slipknot"),
    song("SURFACING", 210, "4/4", "", "Slipknot"),
    song("PSYCHOSOCIAL", 135, "4/4", "", "Slipknot"),
    song("AOV", 133, "4/4", "", "Slipknot"),
    song("LIBERATE", 145, "4/4", "", "Slipknot"),
    song("UNSTAINTED", 200, "4/4", "", "Slipknot"),
    song("WAIT TO BLEED", 190, "4/4", "", "Slipknot"),
    song("Duality", 145, "4/4", "", "Slipknot"),
    song("The Devil in I", 120, "4/4", "", "Slipknot"),
    song("Nero Forte", 100, "4/4", "", "Slipknot"),
    song("Custer", 135, "4/4", "", "Slipknot"),
    song("The Heretic Anthem", 204, "4/4", "", "Slipknot")
  ], "Slipknot Tribute"),
  playlist("Sepultura & Pantera", [
    song("ARISE / DEAD EMBRIONIC CELLS", 120, "4/4", "", "Sepultura"),
    song("TROOPS OF DOOM", 200, "4/4", "", "Sepultura"),
    song("SEPULNATION", 100, "4/4", "", "Sepultura"),
    song("C.F.H.", 114, "4/4", "", "Pantera"),
    song("A NEW LEVEL", 120, "4/4", "", "Pantera"),
    song("REFUSE/RESIST", 105, "4/4", "", "Sepultura"),
    song("TERRITORY", 120, "4/4", "", "Sepultura"),
    song("BIOTECH IS GODZILLA", 220, "4/4", "", "Sepultura"),
    song("PROPAGANDA", 130, "4/4", "", "Sepultura"),
    song("WALK", 116, "4/4", "", "Pantera"),
    song("ATITUDE", 170, "4/4", "", "Sepultura"),
    song("CHOKE", 100, "4/4", "", "Sepultura"),
    song("RATAMAHATTA", 120, "4/4", "", "Sepultura"),
    song("ROOTS", 120, "4/4", "", "Sepultura"),
    song("Inner Self", 190, "4/4", "", "Sepultura"),
    song("Desperate Cry", 130, "4/4", "", "Sepultura"),
    song("Slave New World", 100, "4/4", "", "Sepultura"),
    song("Domination", 140, "4/4", "", "Pantera"),
    song("I'm Broken", 78, "4/4", "", "Pantera")
  ], "Covers Variados"),
  playlist("Unjust Hands", [
    song("UNJUST HANDS", 160, "4/4", "", "Unjust Hands"),
    song("I HATE YOU! (MF)", 180, "4/4", "", "Unjust Hands"),
    song("IMPERIALIST EVIL", 165, "4/4", "", "Unjust Hands"),
    song("HANDS KILLER", 180, "4/4", "", "Unjust Hands"),
    song("WHATS LEFT", 170, "4/4", "", "Unjust Hands"),
    song("LOST TIME", 120, "7/8", "compasso 7/8 autoral", "Unjust Hands"),
    song("Shattered Crown", 190, "4/4", "", "Unjust Hands"),
    song("Echoes of Silence", 140, "4/4", "", "Unjust Hands"),
    song("Crimson Tide", 200, "4/4", "", "Unjust Hands"),
    song("Final Reckoning", 175, "4/4", "", "Unjust Hands"),
    song("Beneath a Broken Sky", 150, "6/8", "", "Unjust Hands")
  ], "Unjust Hands"),
  playlist("Banda New Metal", [
    song("Freak on a Leash", 103, "4/4", "", "Korn"),
    song("My Own Summer (Shove It)", 85, "4/4", "", "Deftones"),
    song("Duality", 145, "4/4", "", "Slipknot"),
    song("Chop Suey!", 127, "4/4", "", "System of a Down"),
    song("Voodoo", 134, "4/4", "", "Godsmack"),
    song("In the End", 105, "4/4", "", "Linkin Park"),
    song("Down with the Sickness", 90, "4/4", "", "Disturbed"),
    song("What Comes Around", 95, "4/4", "", "Ill Ni\xF1o"),
    song("Denial", 105, "4/4", "", "Sevendust"),
    song("Got the Life", 123, "4/4", "", "Korn"),
    song("Rollin' (Air Raid Vehicle)", 100, "4/4", "", "Limp Bizkit"),
    song("Spit It Out", 144, "4/4", "", "Slipknot"),
    song("Toxicity", 117, "4/4", "", "System of a Down"),
    song("Dig", 140, "4/4", "", "Mudvayne"),
    song("Blind", 94, "4/4", "", "Korn"),
    song("Last Resort", 91, "4/4", "", "Papa Roach"),
    song("Wait and Bleed", 93, "4/4", "", "Slipknot"),
    song("Numb", 110, "4/4", "", "Linkin Park"),
    song("Change (In the House of Flies)", 62, "4/4", "", "Deftones"),
    song("Break Stuff", 110, "4/4", "", "Limp Bizkit"),
    song("B.Y.O.B.", 103, "4/4", "", "System of a Down"),
    song("Loco", 98, "4/4", "", "Coal Chamber"),
    song("Bodies", 100, "4/4", "", "Drowning Pool"),
    song("Butterfly", 105, "4/4", "", "Crazy Town"),
    song("Psychosocial", 135, "4/4", "", "Slipknot"),
    song("Coming Undone", 85, "4/4", "", "Korn"),
    song("Headstrong", 90, "4/4", "", "Trapt"),
    song("Snot", 102, "4/4", "", "Snot"),
    song("Be Quiet and Drive", 91, "4/4", "", "Deftones"),
    song("Falling Away from Me", 100, "4/4", "", "Korn"),
    song("The Red", 148, "4/4", "", "Chevelle"),
    song("My Way", 97, "4/4", "", "Limp Bizkit"),
    song("Before I Forget", 127, "4/4", "", "Slipknot"),
    song("Sugar", 131, "4/4", "", "System of a Down"),
    song("Death Blooms", 108, "4/4", "", "Mudvayne"),
    song("Crawling", 105, "4/4", "", "Linkin Park"),
    song("Drive", 91, "4/4", "", "Incubus"),
    song("Everything Ends", 115, "4/4", "", "Slipknot"),
    song("The Game", 112, "4/4", "", "Disturbed"),
    song("Youth of the Nation", 98, "4/4", "", "P.O.D."),
    song("Happy?", 104, "4/4", "", "Mudvayne"),
    song("Push It", 125, "4/4", "", "Static-X"),
    song("Smooth Criminal", 126, "4/4", "", "Alien Ant Farm"),
    song("Between Angels and Insects", 90, "4/4", "", "Papa Roach"),
    song("Papercut", 75, "4/4", "", "Linkin Park"),
    song("Click Click Boom", 89, "4/4", "", "Saliva"),
    song("Points of Authority", 95, "4/4", "", "Linkin Park"),
    song("Faint", 135, "4/4", "", "Linkin Park"),
    song("Aerials", 92, "4/4", "", "System of a Down"),
    song("Alive", 78, "4/4", "", "P.O.D."),
    song("Bulls on Parade", 89, "4/4", "", "Rage Against the Machine"),
    song("Nookie", 98, "4/4", "", "Limp Bizkit"),
    song("Take A Look Around", 102, "4/4", "", "Limp Bizkit"),
    song("Somewhere I Belong", 81, "4/4", "", "Linkin Park"),
    song("Driven Under", 122, "4/4", "", "Seether"),
    song("Through Glass", 110, "4/4", "", "Stone Sour"),
    song("Pardon Me", 135, "4/4", "", "Incubus"),
    song("What I've Done", 120, "4/4", "", "Linkin Park"),
    song("Prayer", 100, "4/4", "", "Disturbed"),
    song("Crawling In The Dark", 115, "4/4", "", "Hoobastank"),
    song("Stupify", 92, "4/4", "", "Disturbed"),
    song("Bleed It Out", 140, "4/4", "", "Linkin Park"),
    song("One Step Closer", 95, "4/4", "", "Linkin Park"),
    song("A Place for My Head", 133, "4/4", "", "Linkin Park"),
    song("Shimmy", 138, "6/8", "", "System of a Down"),
    song("Deer Dance", 125, "6/8", "", "System of a Down"),
    song("Pharmaecopia", 125, "6/8", "", "Mudvayne"),
    song("Solace", 80, "12/8", "", "Sevendust"),
    song("Mercy", 120, "6/8", "", "Sevendust"),
    song("Streamline", 90, "5/4", "", "System of a Down"),
    song("The Mountain", 100, "3/4", "", "Three Days Grace"),
    song("Inner Vision", 146, "6/8", "", "System of a Down"),
    song("Mind", 72, "6/8", "", "System of a Down"),
    song("L.E.D.", 130, "7/4", "", "Tallah"),
    song("Just So You Know", 145, "13/8", "", "American Head Charge"),
    song("Everything Ends", 115, "4/4", "", "Slipknot"),
    song("Skin It Back", 110, "3/4", "", "Static-X"),
    song("I'm With You", 105, "6/8", "", "Avril Lavigne"),
    song("Vermilion Pt. 2", 60, "3/4", "", "Slipknot")
  ], "Banda New Metal"),
  playlist("Prog Rock", [
    song("Pull Me Under", 104, "4/4", "", "Dream Theater"),
    song("Tom Sawyer", 87, "4/4", "", "Rush"),
    song("Money", 123, "7/4", "muda para 4/4", "Pink Floyd"),
    song("Take Five", 174, "5/4", "", "The Dave Brubeck Quartet"),
    song("The Ocean", 90, "7/8", "alterna com 4/4", "Led Zeppelin"),
    song("Metropolis\u2014Part I", 130, "4/4", "", "Dream Theater"),
    song("YYZ", 140, "5/4", "", "Rush"),
    song("As I Am", 122, "4/4", "", "Dream Theater"),
    song("Limelight", 132, "4/4", "", "Rush"),
    song("Schism", 107, "12/8", "compasso vari\xE1vel", "Tool"),
    song("The Spirit of Radio", 135, "4/4", "", "Rush"),
    song("Octavarium", 118, "5/4", "", "Dream Theater"),
    song("Lateralus", 90, "9/8", "sequ\xEAncia de Fibonacci", "Tool"),
    song("La Villa Strangiato", 136, "4/4", "", "Rush")
  ], "Covers Variados"),
  playlist("Industrial Metal", [
    song("Du Hast", 125, "4/4", "", "Rammstein"),
    song("Dragula", 126, "4/4", "", "Rob Zombie"),
    song("Push It", 135, "4/4", "", "Static-X"),
    song("N.W.O.", 140, "4/4", "", "Ministry"),
    song("Closer", 90, "4/4", "", "Nine Inch Nails"),
    song("Sonne", 75, "4/4", "", "Rammstein"),
    song("Head Like a Hole", 115, "4/4", "", "Nine Inch Nails"),
    song("Ich Will", 128, "4/4", "", "Rammstein"),
    song("Superbeast", 118, "4/4", "", "Rob Zombie"),
    song("The Dope Show", 130, "4/4", "", "Marilyn Manson"),
    song("Just One Fix", 145, "4/4", "", "Ministry"),
    song("Terrible Lie", 115, "4/4", "", "Nine Inch Nails")
  ], "Covers Variados"),
  playlist("Rock Nacional", [
    song("Que Pa\xEDs \xC9 Este", 160, "4/4", "", "Legi\xE3o Urbana"),
    song("Garota Nacional", 130, "4/4", "", "Skank"),
    song("Epit\xE1fio", 80, "4/4", "", "Tit\xE3s"),
    song("Meu Erro", 145, "4/4", "", "Os Paralamas do Sucesso"),
    song("Natasha", 140, "4/4", "", "Capital Inicial"),
    song("F\xE1cil", 85, "4/4", "", "Jota Quest"),
    song("Proibida Pra Mim (Grazon)", 95, "4/4", "", "Charlie Brown Jr."),
    song("Anna Julia", 140, "4/4", "", "Los Hermanos"),
    song("Malandragem", 90, "4/4", "", "C\xE1ssia Eller"),
    song("Vou Deixar", 130, "4/4", "", "Skank"),
    song("Primeiros Erros", 150, "4/4", "", "Capital Inicial"),
    song("Mulher de Fases", 100, "4/4", "", "Raimundos")
  ], "Rock Nacional"),
  playlist("Indie Rock", [
    song("Last Nite", 104, "4/4", "", "The Strokes"),
    song("Do I Wanna Know?", 85, "4/4", "", "Arctic Monkeys"),
    song("Take Me Out", 105, "4/4", "", "Franz Ferdinand"),
    song("Mr. Brightside", 148, "4/4", "", "The Killers"),
    song("Wake Up", 120, "4/4", "", "Arcade Fire"),
    song("Evil", 130, "4/4", "", "Interpol"),
    song("Maps", 120, "4/4", "", "Yeah Yeah Yeahs"),
    song("Float On", 101, "4/4", "", "Modest Mouse"),
    song("Reptilia", 156, "4/4", "", "The Strokes"),
    song("Somebody Told Me", 138, "4/4", "", "The Killers"),
    song("R U Mine?", 97, "4/4", "", "Arctic Monkeys"),
    song("Obstacle 1", 148, "4/4", "", "Interpol")
  ], "Covers Variados"),
  playlist("Samba", [
    song("Aquarela do Brasil", 130, "2/4", "", "Ary Barroso"),
    song("Mas Que Nada", 128, "2/4", "", "Jorge Ben Jor"),
    song("Pa\xEDs Tropical", 120, "2/4", "", "Jorge Ben Jor"),
    song("Taj Mahal", 124, "2/4", "", "Jorge Ben Jor"),
    song("Trem das Onze", 116, "2/4", "", "Adoniran Barbosa"),
    song("A Banda", 112, "2/4", "", "Chico Buarque"),
    song("Apesar de Voc\xEA", 118, "2/4", "", "Chico Buarque"),
    song("Samba de Janeiro", 132, "2/4", "", "Bellini"),
    song("Magalenha", 126, "2/4", "", "S\xE9rgio Mendes"),
    song("Deixa a Vida Me Levar", 96, "2/4", "", "Zeca Pagodinho"),
    song("Camar\xE3o que Dorme a Onda Leva", 100, "2/4", "", "Zeca Pagodinho"),
    song("\xC1guas de Mar\xE7o", 120, "2/4", "", "Tom Jobim"),
    song("Garota de Ipanema", 130, "4/4", "", "Tom Jobim"),
    song("Chega de Saudade", 138, "2/4", "", "Jo\xE3o Gilberto"),
    song("O Mundo \xE9 um Moinho", 92, "4/4", "", "Cartola")
  ], "Samba"),
  playlist("Sertanejo", [
    song("Evid\xEAncias", 75, "4/4", "", "Chit\xE3ozinho & Xoror\xF3"),
    song("Fio de Cabelo", 82, "4/4", "", "Chit\xE3ozinho & Xoror\xF3"),
    song("Ai Se Eu Te Pego", 130, "4/4", "", "Michel Tel\xF3"),
    song("Cuida Bem Dela", 88, "4/4", "", "Henrique & Juliano"),
    song("Anti-Amor", 92, "4/4", "", "Gusttavo Lima"),
    song("Balada Boa", 130, "4/4", "", "Gusttavo Lima"),
    song("Saudade Sua", 86, "4/4", "", "Jorge & Mateus"),
    song("Os Anjos Cantam", 78, "4/4", "", "Jorge & Mateus"),
    song("Logo Eu", 90, "4/4", "", "Jorge & Mateus"),
    song("Cheia de Manias", 80, "4/4", "", "Ra\xE7a Negra"),
    song("Romaria", 72, "3/4", "", "Renato Teixeira"),
    song("Tocando em Frente", 76, "4/4", "", "Almir Sater"),
    song("Cora\xE7\xE3o Apaixonado", 84, "4/4", "", "Leonardo"),
    song("Telefone Mudo", 80, "4/4", "", "Zez\xE9 Di Camargo & Luciano"),
    song("\xC9 o Amor", 74, "4/4", "", "Zez\xE9 Di Camargo & Luciano")
  ], "Sertanejo"),
  playlist("Sertanejo Universit\xE1rio", [
    song("Ai Se Eu Te Pego", 130, "4/4", "", "Michel Tel\xF3"),
    song("Camaro Amarelo", 96, "4/4", "", "Munhoz & Mariano"),
    song("Te Assumi pro Brasil", 90, "4/4", "", "Matheus & Kauan"),
    song("Que Sorte a Nossa", 92, "4/4", "", "Matheus & Kauan"),
    song("Atrasadinha", 88, "4/4", "", "Felipe Ara\xFAjo"),
    song("Bem Pior Que Eu", 86, "4/4", "", "Mar\xEDlia Mendon\xE7a"),
    song("Infiel", 84, "4/4", "", "Mar\xEDlia Mendon\xE7a"),
    song("Eu Sei de Cor", 80, "4/4", "", "Mar\xEDlia Mendon\xE7a"),
    song("Hoje", 82, "4/4", "", "Maiara & Maraisa"),
    song("Medo Bobo", 88, "4/4", "", "Maiara & Maraisa"),
    song("Largado \xE0s Tra\xE7as", 90, "4/4", "", "Z\xE9 Neto & Cristiano"),
    song("Notifica\xE7\xE3o Preferida", 92, "4/4", "", "Z\xE9 Neto & Cristiano"),
    song("Tijol\xE3o", 86, "4/4", "", "Jorge & Mateus"),
    song("Propaganda", 88, "4/4", "", "Jorge & Mateus"),
    song("Pra Voc\xEA Acreditar", 84, "4/4", "", "Cristiano Ara\xFAjo")
  ], "Sertanejo Universit\xE1rio")
];
var EX_BAND = "\u{1F393} Exerc\xEDcios";
function lvl(startBpm, targetBpm) {
  const diff = targetBpm - startBpm;
  if (targetBpm >= 140 || diff >= 60) return "\u{1F534} Avan\xE7ado";
  if (targetBpm >= 100 || diff >= 35) return "\u{1F7E1} Intermedi\xE1rio";
  return "\u{1F7E2} Iniciante";
}
function ex(name, startBpm, targetBpm, ts, durationSec, extra = "") {
  const notes = `${lvl(startBpm, targetBpm)} \xB7 Progress\xE3o: ${startBpm} \u2192 ${targetBpm} BPM${extra ? " \xB7 " + extra : ""}`;
  return { id: crypto.randomUUID(), name, bpm: startBpm, timeSignature: ts, notes, artist: "", duration: durationSec };
}
var exercisePlaylists = [
  playlist("\u{1F941} Bateria", [
    ex("Rudimento: Single Stroke Roll", 60, 120, "4/4", 300),
    ex("Rudimento: Double Stroke Roll", 60, 100, "4/4", 300),
    ex("Rudimento: Paradiddle", 60, 100, "4/4", 300),
    ex("Groove B\xE1sico Rock", 70, 110, "4/4", 240),
    ex("Groove Funk (ghost notes)", 75, 100, "4/4", 300),
    ex("Blast Beat Metal", 100, 180, "4/4", 180),
    ex("Shuffle Blues", 65, 95, "12/8", 240),
    ex("Polirritmo 3 contra 4", 60, 90, "4/4", 300),
    ex("Doubles no bumbo", 80, 160, "4/4", 300),
    ex("Independ\xEAncia m\xE3os e p\xE9s", 60, 100, "4/4", 360)
  ], EX_BAND),
  playlist("\u{1F3B9} Piano / Teclado", [
    ex("Escalas Maiores (C, G, D)", 60, 120, "4/4", 300),
    ex("Escalas Menores (Am, Em)", 60, 120, "4/4", 300),
    ex("Arpejos B\xE1sicos", 60, 100, "4/4", 300),
    ex("Acordes Tr\xEDades", 70, 110, "4/4", 240),
    ex("Hanon Exerc\xEDcio 1", 60, 120, "4/4", 300),
    ex("Hanon Exerc\xEDcio 2", 60, 120, "4/4", 300),
    ex("Invers\xE3o de Acordes", 70, 100, "4/4", 300),
    ex("Oitavas Saltadas", 60, 100, "4/4", 240),
    ex("Tremolos", 60, 120, "4/4", 300),
    ex("Leitura \xE0 Primeira Vista", 60, 80, "4/4", 600)
  ], EX_BAND),
  playlist("\u{1F3BB} Cordas (Violino/Viola/Cello)", [
    ex("Arco: Detach\xE9 b\xE1sico", 60, 100, "4/4", 300),
    ex("Escalas em D\xF3 Maior", 60, 100, "4/4", 300),
    ex("Escalas em Sol Maior", 60, 100, "4/4", 300),
    ex("Mudan\xE7a de Posi\xE7\xE3o (1\xAA\u21923\xAA)", 50, 80, "4/4", 300),
    ex("Spiccato", 60, 120, "4/4", 240),
    ex("Duplas Cordas", 50, 90, "4/4", 300),
    ex("Vibrato Cont\xEDnuo", 40, 70, "4/4", 300),
    ex("Pizzicato R\xEDtmico", 70, 120, "4/4", 240),
    ex("Trinos", 60, 100, "4/4", 300),
    ex("Leitura R\xEDtmica", 60, 90, "4/4", 480)
  ], EX_BAND),
  playlist("\u{1F3B8} Guitarra / Baixo", [
    ex("Alternate Picking", 60, 140, "4/4", 300),
    ex("Escala Pentat\xF4nica", 60, 120, "4/4", 300),
    ex("Power Chords", 70, 120, "4/4", 240),
    ex("Sweep Picking", 50, 100, "4/4", 300),
    ex("Legato (hammer-on/pull-off)", 60, 120, "4/4", 300),
    ex("Fingerstyle B\xE1sico", 60, 100, "4/4", 300),
    ex("Palm Mute Metal", 100, 180, "4/4", 240),
    ex("Slap Baixo", 60, 110, "4/4", 300),
    ex("Tapping", 60, 120, "4/4", 300),
    ex("Improviso sobre backing", 70, 100, "4/4", 600)
  ], EX_BAND),
  playlist("\u{1F3BA} Sopros", [
    ex("Escalas Longas (notas sustentadas)", 50, 80, "4/4", 300),
    ex("Escalas Crom\xE1ticas", 60, 100, "4/4", 300),
    ex("Staccato", 70, 120, "4/4", 240),
    ex("Intervalos (3\xAAs, 5\xAAs, 8\xAAs)", 60, 100, "4/4", 300),
    ex("Tonguing Duplo", 80, 140, "4/4", 240),
    ex("Slur e Legato", 60, 100, "4/4", 300),
    ex("Flexibilidade de Embocadura", 50, 80, "4/4", 360),
    ex("Arpejos de Dominante", 60, 100, "4/4", 300),
    ex("Improvisa\xE7\xE3o Blues", 70, 110, "4/4", 480),
    ex("Leitura R\xEDtmica Avan\xE7ada", 60, 100, "4/4", 480)
  ], EX_BAND),
  playlist("\u{1F399}\uFE0F Canto / Voz", [
    ex("Aquecimento: Escalas Vocais", 60, 100, "4/4", 300),
    ex("Ritmo e Dic\xE7\xE3o", 80, 120, "4/4", 240),
    ex("S\xEDlabas em Tempo (bah-bah)", 70, 120, "4/4", 300),
    ex("Respira\xE7\xE3o Diafragm\xE1tica", 50, 70, "4/4", 360),
    ex("Melisma (ornamentos vocais)", 60, 90, "4/4", 300)
  ], EX_BAND)
];

// src/lib/mcp/tools/list-default-playlists.ts
var list_default_playlists_default = defineTool({
  name: "list_default_playlists",
  title: "List default BeatMaster playlists",
  description: "List BeatMaster's built-in playlists (band setlists and instrument exercises), each with their songs, BPMs, and time signatures.",
  inputSchema: {
    include_exercises: z.boolean().optional().describe("Include the \u{1F393} Exerc\xEDcios instrument-training playlists. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ include_exercises }) => {
    const includeExercises = include_exercises ?? true;
    const all = includeExercises ? [...defaultPlaylists, ...exercisePlaylists] : defaultPlaylists;
    const summary = all.map((p) => ({
      name: p.name,
      band: p.band,
      songCount: p.songs.length,
      songs: p.songs.map((s) => ({
        name: s.name,
        artist: s.artist,
        bpm: s.bpm,
        timeSignature: s.timeSignature,
        durationSeconds: s.duration,
        notes: s.notes
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { playlists: summary }
    };
  }
});

// src/lib/mcp/tools/search-music-metadata.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var MB_URL = "https://musicbrainz.org/ws/2/recording";
var search_music_metadata_default = defineTool2({
  name: "search_music_metadata",
  title: "Search music metadata (MusicBrainz)",
  description: "Search the MusicBrainz recording database for a song/artist. Returns matches with title, artist, release, and MBID \u2014 useful for enriching BeatMaster setlists.",
  inputSchema: {
    query: z2.string().min(1).max(200).describe("Song title, artist, or 'title artist' query."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (1-25). Default 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const url = `${MB_URL}?query=${encodeURIComponent(query)}&limit=${limit ?? 5}&fmt=json`;
    try {
      const res = await fetch(url, {
        headers: { "User-Agent": "BeatMaster-MCP/0.1.0 (https://beatmaster.lovable.app)" }
      });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `MusicBrainz error: ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      const results = (data.recordings ?? []).map((r) => ({
        title: r.title,
        artist: r["artist-credit"]?.map((a) => a.name).join(", "),
        release: r.releases?.[0]?.title,
        lengthMs: r.length,
        mbid: r.id,
        score: r.score
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
        structuredContent: { results }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Fetch failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/bpm-utils.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var bpm_utils_default = defineTool3({
  name: "bpm_utils",
  title: "BPM & tempo utilities",
  description: "Convert between BPM, milliseconds per beat, and beats/bars for a given duration and time signature. Handy for planning setlist timing.",
  inputSchema: {
    bpm: z3.number().min(20).max(400).describe("Tempo in beats per minute."),
    timeSignature: z3.string().optional().describe("Time signature like '4/4', '3/4', '6/8'. Defaults to '4/4'."),
    durationSeconds: z3.number().min(0).optional().describe("Optional song duration; if provided, returns total beats and bars.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bpm, timeSignature, durationSeconds }) => {
    const ts = timeSignature ?? "4/4";
    const [numStr] = ts.split("/");
    const beatsPerBar = parseInt(numStr, 10) || 4;
    const msPerBeat = 6e4 / bpm;
    const result = {
      bpm,
      timeSignature: ts,
      beatsPerBar,
      msPerBeat: Math.round(msPerBeat * 100) / 100,
      secondsPerBar: Math.round(msPerBeat * beatsPerBar / 10) / 100
    };
    if (durationSeconds != null) {
      const totalBeats = durationSeconds * bpm / 60;
      result.totalBeats = Math.round(totalBeats * 100) / 100;
      result.totalBars = Math.round(totalBeats / beatsPerBar * 100) / 100;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "beatmaster-mcp",
  title: "BeatMaster MCP",
  version: "0.1.0",
  instructions: "Tools for BeatMaster \u2014 a performance app with metronome, setlist, and sampler. Use `list_default_playlists` to browse built-in band/exercise setlists, `search_music_metadata` to look up songs on MusicBrainz, and `bpm_utils` for tempo/bar calculations.",
  tools: [list_default_playlists_default, search_music_metadata_default, bpm_utils_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
